version: '2'
services:
    ople_sioe-app:
        image: ople_sioe
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://ople_sioe-mysql:3306/ople_sioe?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    ople_sioe-mysql:
        extends:
            file: mysql.yml
            service: ople_sioe-mysql
